export const listaUsuariosLiberados = [
  "SISPLAN.WILLIAN.GUERRA",
  "SISPLAN.ELITON.SOUZA",
  "SISPLAN.FABRICIO.MAZIERO",
  "SISPLAN.GUILHERME.THEINDL",
  "SISPLAN.TIAGO.NASCIMENTO",
  "SISPLAN.GABRIEL.DALLAROSA",
  "SISPLAN.THIAGO.GONCALVES",
  "SISPLAN.EDENILSON.ANDRADE",
  "SISPLAN.JEAN.ROSA",
  "SISPLAN.MAICON.BERKEMBROCK",
  "SISPLAN.OSMAR.SCHWARTZ",
];